import React, { useState, useEffect } from 'react'
import { Brush, CheckCircle, Trash2, ArrowRight, ShieldAlert, Sparkles } from 'lucide-react'

export default function DataCleaning({ currentProject, activeDataset, setActiveDataset }) {
  const [recommendations, setRecommendations] = useState([])
  const [cleanHistory, setCleanHistory] = useState([])
  const [isLoading, setIsLoading] = useState(false)
  const [selectedRecommendations, setSelectedRecommendations] = useState({}) // { rec_id: boolean }
  const [customParams, setCustomParams] = useState({}) // { rec_id: { key: val } }

  // Populate recommendations from activeDataset
  useEffect(() => {
    if (activeDataset) {
      // Recommendations are fetched from activeDataset if loaded, or we fetch them
      if (activeDataset.recommendations) {
        setRecommendations(activeDataset.recommendations)
        initializeSelection(activeDataset.recommendations)
      } else {
        fetchRecommendations()
      }

      // If dataset has clean history, load it
      if (activeDataset.summary?.clean_history) {
        setCleanHistory(activeDataset.summary.clean_history)
      }
    }
  }, [activeDataset])

  const initializeSelection = (recs) => {
    const sel = {}
    recs.forEach(r => {
      sel[r.id] = true // accept by default
    })
    setSelectedRecommendations(sel)
  }

  const fetchRecommendations = async () => {
    if (!activeDataset) return
    setIsLoading(true)
    try {
      const res = await fetch(`https://ai-powered-automated-data-analytics.onrender.com/api/v1/data/${activeDataset.id}/preview`)
      if (res.ok) {
        // Simple scan on active dataset to fetch info
        const data = await res.json()
      }
    } catch (e) {
      console.error(e)
    } finally {
      setIsLoading(false)
    }
  }

  const toggleSelect = (id) => {
    setSelectedRecommendations(prev => ({
      ...prev,
      [id]: !prev[id]
    }))
  }

  const handleCustomParamChange = (recId, key, value) => {
    setCustomParams(prev => ({
      ...prev,
      [recId]: {
        ...prev[recId],
        [key]: value
      }
    }))
  }

  const handleExecuteClean = async () => {
    if (!activeDataset) return
    setIsLoading(true)

    // Compile list of actions to apply
    const actionsToRun = recommendations
      .filter(r => selectedRecommendations[r.id])
      .map(r => {
        const item = { ...r }
        // Merge custom parameters if user changed them
        if (customParams[r.id]) {
          item.parameters = {
            ...item.parameters,
            ...customParams[r.id]
          }
          // If user customized fill value, change action to custom
          if (r.action.startsWith("fill_") && customParams[r.id].value !== undefined) {
            item.action = "fill_custom"
          }
        }
        return item
      })

    if (actionsToRun.length === 0) {
      alert("No cleaning recommendations selected.")
      setIsLoading(false)
      return
    }

    try {
      const formData = new FormData()
      formData.append('accepted_actions', JSON.stringify(actionsToRun))

      const res = await fetch(`https://ai-powered-automated-data-analytics.onrender.com/api/v1/data/${activeDataset.id}/clean`, {
        method: 'POST',
        body: formData
      })

      if (res.ok) {
        const data = await res.json()
        setCleanHistory(data.history)
        setRecommendations(data.remaining_recommendations)
        initializeSelection(data.remaining_recommendations)

        // Update active dataset columns/rows
        setActiveDataset(prev => ({
          ...prev,
          rows: data.rows,
          columns: data.columns,
          summary: data.summary,
          recommendations: data.remaining_recommendations
        }))
      } else {
        const err = await res.json()
        alert(err.detail || "Failed to execute cleaning pipeline.")
      }
    } catch (e) {
      alert("Error sending cleaning payload to ")
    } finally {
      setIsLoading(false)
    }
  }

  if (!activeDataset) {
    return (
      <div className="glass-panel border-indigo-950 rounded-2xl p-12 text-center flex flex-col items-center justify-center gap-4">
        <Brush size={48} className="text-indigo-400" />
        <h4 className="text-lg font-bold text-white">No Dataset Loaded</h4>
        <p className="text-sm text-slate-400">Please go to Home & Upload to import a data source first.</p>
      </div>
    )
  }

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Title */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold font-outfit text-white">Data Cleaning Agent</h2>
          <p className="text-xs text-slate-400 mt-1">Accept, reject, or customize cleaning recommendations generated by the profiling agent.</p>
        </div>

        <button
          onClick={handleExecuteClean}
          disabled={isLoading || recommendations.length === 0}
          className="bg-indigo-600 hover:bg-indigo-500 font-semibold px-6 py-2.5 rounded-xl transition-all duration-200 shadow-md shadow-indigo-600/10 flex items-center gap-2 text-sm disabled:opacity-55 disabled:cursor-not-allowed"
        >
          <Sparkles size={16} />
          <span>Execute Clean</span>
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Recommendations list */}
        <div className="lg:col-span-2 space-y-4">
          <div className="glass-card rounded-2xl p-6 space-y-4">
            <h3 className="text-md font-bold text-white uppercase tracking-wider flex items-center gap-2">
              <ShieldAlert size={16} className="text-indigo-400" />
              <span>Agent Recommendations ({recommendations.length})</span>
            </h3>

            {recommendations.length === 0 ? (
              <div className="p-8 text-center bg-slate-900/10 rounded-xl border border-slate-850">
                <CheckCircle size={32} className="text-emerald-500 mx-auto mb-2" />
                <div className="text-sm font-semibold text-slate-200">No anomalies detected!</div>
                <p className="text-xs text-slate-500 mt-1">Your dataset is clean and ready for analytical queries.</p>
              </div>
            ) : (
              <div className="space-y-4">
                {recommendations.map((rec) => {
                  const isChecked = selectedRecommendations[rec.id]
                  return (
                    <div
                      key={rec.id}
                      className={`p-4 rounded-xl border transition-all ${isChecked
                          ? 'bg-indigo-950/20 border-indigo-900/60'
                          : 'bg-slate-900/10 border-slate-850 opacity-60'
                        }`}
                    >
                      <div className="flex items-start gap-4">
                        <input
                          type="checkbox"
                          checked={!!isChecked}
                          onChange={() => toggleSelect(rec.id)}
                          className="mt-1.5 rounded text-indigo-600 focus:ring-indigo-500"
                        />
                        <div className="flex-1 space-y-2">
                          <div className="flex items-center gap-2">
                            <span className="text-xs font-bold px-2 py-0.5 rounded bg-slate-800 text-indigo-400 uppercase tracking-wide">
                              {rec.column}
                            </span>
                            <span className="text-xs text-slate-500">• {rec.issue}</span>
                          </div>

                          <div className="text-sm text-slate-200 font-medium">
                            {rec.recommendation}
                          </div>

                          {/* Customizations options */}
                          {isChecked && rec.action.startsWith("fill_") && (
                            <div className="pt-2 flex items-center gap-3">
                              <span className="text-xs text-slate-500">Custom Value:</span>
                              <input
                                type="text"
                                placeholder="Value..."
                                value={customParams[rec.id]?.value !== undefined ? customParams[rec.id].value : (rec.parameters.value || '')}
                                onChange={(e) => handleCustomParamChange(rec.id, 'value', e.target.value)}
                                className="glass-input text-xs rounded px-2.5 py-1 max-w-[120px]"
                              />
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  )
                })}
              </div>
            )}
          </div>
        </div>

        {/* Cleaning Log/History Panel */}
        <div className="lg:col-span-1 space-y-6">
          <div className="glass-card rounded-2xl p-6 space-y-4">
            <h3 className="text-md font-bold text-white uppercase tracking-wider flex items-center gap-2">
              <Brush size={16} className="text-indigo-400" />
              <span>Clean Actions Applied</span>
            </h3>

            {cleanHistory.length === 0 ? (
              <p className="text-xs text-slate-500 leading-relaxed">No operations applied yet. Select recommendations and execute clean.</p>
            ) : (
              <div className="space-y-3 max-h-[300px] overflow-y-auto pr-1">
                {cleanHistory.map((item, idx) => (
                  <div key={idx} className="p-3 bg-slate-900/30 rounded-lg border border-slate-850 text-xs text-slate-300 flex items-start gap-2.5">
                    <span className="text-emerald-500 font-bold">✓</span>
                    <span>{item}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
